<?php

namespace Container9HFVnSH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZHkJdKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZHkJd_K' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZHkJd_K'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'adresseLivraisonRepository' => ['privates', 'App\\Repository\\AdresseLivraisonRepository', 'getAdresseLivraisonRepositoryService', true],
        ], [
            'adresseLivraisonRepository' => 'App\\Repository\\AdresseLivraisonRepository',
        ]);
    }
}
